# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31b09dd58c6db7f005a739290da1a9f94c56d5b733491e2d6b2a241a0558af1cb1b251e85350b40faca8cb0c9dc54ad92365990b66ed9ec90b6678964c2ed25

test:
  secret_key_base: 985adbdb8db5fe9d404e299af3d6d017e79f778b4de6abd8abb7bbd949a83a638066233c4c1c5c15506edfd48a343c0fde48732b75ac891c6b19d23e8c7f0b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
